### ISSUE TITLE
Occurring UI lag while insertion process

### ISSUE THREAD

**Issue by strawb3rryx7** [k-lpmg/RealmWrapper#5]
Hi @k-lpmg! 

I'm trying to insert a batch of data (~10k, 15k). UI gets laggy while insertion process, and i'm using the different thread instead of main thread. 

**Some details about getting lag of UI:**

Bad scroll experience of sliding table / collection view. UI is not freezing entirely. It's happening for a second, really short time but affects UI experience.

You can see in below;

<img width="940" alt="ekran resmi 2019-02-20 02 42 12" src="https://user-images.githubusercontent.com/9626765/53055547-28d2ab80-34b9-11e9-993e-aefa148207b1.png">
<img width="764" alt="ekran resmi 2019-02-20 02 39 25" src="https://user-images.githubusercontent.com/9626765/53055551-2d975f80-34b9-11e9-861d-5e8c91c4efcf.png">

and last one;

i'm calling that method like that;

<img width="616" alt="ekran resmi 2019-02-20 02 43 23" src="https://user-images.githubusercontent.com/9626765/53055589-4dc71e80-34b9-11e9-92fa-9c97aa33b44a.png">

**Comment by k-lpmg** [comment]
Hi @strawb3rryx7!
Thank you very much for finding this issue.

## Issue
https://github.com/k-lpmg/RealmWrapper/blob/1e5c1f0251cf66e0b3d52232a5e6750638de408e/Sources/RealmWrapper/RealmManageable.swift#L130

transaction function in RealmManageable is calling refresh of the realm.
This code is being called on the completionQueue parameter of the transaction.
The default value of completionQueue is set to main queue.

Since the transaction of realm runs in writeQueue, if you set writeQueue to non main queue, it does not affect UI, but after the transaction is done, refresh is executed in completionQueue, so UI stopped for a very short time.

## Solution
I take this issue seriously and will release the 1.2.0 version after fixing the issue through testing.
Until 1.2.0 is released, in 1.1.4 version, completionQueue will also fix the UI hang for a moment if you put non main queue.
``` swift
func insertAll(_ friendships: [Friendship]) {
    rm.transaction(writeQueue: DispatchQueue.realmBg, isSync: false, writeHandler: { (realm) in
        realm.add(friendships, update: true)
    }, completionQueue: DispatchQueue.realmBg)
}
```

**Comment by strawb3rryx7** [comment]
Thanks for your quick action @k-lpmg ✋🏼 I applied your hot fix. Then I'll check out when it'll be released, and there is an another issue but I'm not sure is it related with this issue.

Realm file size getting large quickly, when these batch insertions are done, I'm checking the documents & file size from `General` -> `iPhone Storage`, I see 40 MB and above.

**Comment by strawb3rryx7** [comment]
Bump! I've been a chance to try your hotfix now. Also the problem is still exists.

**Comment by k-lpmg** [comment]
I released version 1.2.0 which is a revised version of this issue.
In addition, the ability to insert multiple realm objects at once is added to Example.

You no longer need to set the completionQueue in your insertAll method because of this issue. 😁

**Comment by strawb3rryx7** [comment]
Thanks for your all effort. Do you have any idea about database size which I mentioned in above? 😊

**Comment by k-lpmg** [comment]
Sorry. I have no idea about database size. 😅
